package apps.jan.rendezvous;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * The Local Groups Database class is used for the
 * purpose of managing the clients connection to
 * it's own sqlite master.
 */
public class LocalGroupsDatabase extends SQLiteOpenHelper {

    private static final int DATABASE_VERSION = 1;
    public static final String DATABASE_NAME = "LOCAL_GROUPS.db";

    public LocalGroupsDatabase(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        // TODO Auto-generated method stub

    }

    // the group_num field is a string because it's generated by
    // the client with UUID.
    public static void createGroupTable(SQLiteDatabase db, String group_num){
        String query = GroupsDataFormat.genTableQuery(group_num);
        db.execSQL(query);
    }

}
